name: homepage_project
description: "A new Flutter project."

# The following line prevents accidental publication to pub.dev.
publish_to: 'none' # Remove this line if you want to publish the package.

# Application versioning.
version: 1.0.0+1

# Dart SDK version requirement.
environment:
  sdk: ">=3.0.0 <4.0.0" # Adjusted for clarity and to support a broader range if needed.

dependencies:
  flutter:
    sdk: flutter

  # Flutter and third-party dependencies.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  http_log: ^0.1.1
  shimmer: ^2.0.0
  flutter_secure_storage: ^8.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_inappwebview: ^6.1.5
  marquee: ^2.3.0
  qr_flutter: ^4.1.0
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2
  # video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules for better coding practices.
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  # Asset management.
  assets:
    - assets/images/
    - assets/images/category/
    - assets/icons/
    - assets/categories.json
    - assets/images/logo_game.png
    - assets/images/logo-Old.png
    - assets/images/reels.png
    # - images/a_dot_ham.jpeg

  # Example custom fonts (uncomment if needed).
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700

  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-Old.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo-Old.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo-Old.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo-Old.png"
