name: homepage_project
description: "A new Flutter project."

# The following line prevents accidental publication to pub.dev.
publish_to: 'none' # Remove this line if you want to publish the package.

# Application versioning.
version: 1.0.0+1

# Dart SDK version requirement.
environment:
  sdk: ">=3.0.0 <4.0.0" # Adjusted for clarity and to support a broader range if needed.

dependencies:
  flutter:
    sdk: flutter

  # Flutter and third-party dependencies.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  http_log: ^0.1.1
  shimmer: ^2.0.0
  flutter_secure_storage: ^8.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_inappwebview: ^6.1.5
  marquee: ^2.3.0
  # video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules for better coding practices.
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Asset management.
  assets:
    - assets/images/
    - assets/images/category/
    - assets/icons/
    - assets/categories.json
    - assets/images/logo_game.png
    - assets/images/reels.png
    # Example asset placeholders:
    # - assets/images/icon-logo.png
    # - images/a_dot_ham.jpeg

  # Example custom fonts (uncomment if needed).
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
